import unreal,pathlib,json,hashlib
R=pathlib.Path('C:/Users/mikef/Documents/Codex/2026-09-30/task/CampusCenter-new-plans');D=R/'downstream/furniture_art_v26_r01/fitness_support_patch_r01';P=pathlib.Path(unreal.Paths.project_dir()).resolve();L=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem);A=unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
def snap():
 out={}
 for a in A.get_all_level_actors():
  c=getattr(a,'static_mesh_component',None);out[a.get_name()]={'label':a.get_actor_label(),'mesh':c.static_mesh.get_path_name() if c and c.static_mesh else None,'materials':[c.get_material(i).get_path_name() for i in range(c.get_num_materials())] if c else [],'location':a.get_actor_location().to_tuple(),'rotation':{'pitch':a.get_actor_rotation().pitch,'yaw':a.get_actor_rotation().yaw,'roll':a.get_actor_rotation().roll},'scale':a.get_actor_scale3d().to_tuple(),'hidden':bool(a.get_editor_property('hidden')),'collision':a.get_actor_enable_collision(),'component_collision':str(c.get_collision_enabled()) if c else None}
 return out
assert L.load_level('/Game/Campus/Maps/CampusCenter_FA26_Desktop_R15');before=snap();target='/Game/Campus/Maps/CampusCenter_FA26_Desktop_R21_Support';assert L.load_level(target);after=snap();assert set(before)==set(after);changes=[k for k in before if before[k]!=after[k]];assert changes==['StaticMeshActor_1510'],changes
old=before[changes[0]];new=after[changes[0]];assert all(old[k]==new[k] for k in old if k not in ['mesh','materials'])
a=next(x for x in A.get_all_level_actors() if x.get_name()==changes[0]);n=a.static_mesh_component.static_mesh;oldmesh=unreal.load_asset(old['mesh']);slots=n.get_editor_property('static_materials');materials=[{'slot':str(s.material_slot_name),'path':a.static_mesh_component.get_material(i).get_path_name(),'nanite_usage':a.static_mesh_component.get_material(i).get_base_material().get_editor_property('used_with_nanite')} for i,s in enumerate(slots)];allowed=json.loads((D/'material-compatibility.json').read_text()); aliases={x['compatibility_clone']:x['source'] for x in allowed};assert {aliases.get(x['path'],x['path']) for x in materials}==set(old['materials']);nanite=bool(n.get_editor_property('nanite_settings').enabled);assert nanite==bool(oldmesh.get_editor_property('nanite_settings').enabled);assert not nanite or all(x['nanite_usage'] for x in materials)
file=P/'Content/Campus/Maps/CampusCenter_FA26_Desktop_R21_Support.umap';mf=P/'Content/Campus/FitnessSupportR26R01/Runtime/FA26_FitnessSupport_U218_R06.uasset';proof={'map':target,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest(),'changed_actor_names':changes,'actor_label':new['label'],'old_mesh':old['mesh'],'new_mesh':new['mesh'],'new_mesh_file':str(mf),'new_mesh_sha256':hashlib.sha256(mf.read_bytes()).hexdigest(),'materials':materials,'nanite_matches_original':True,'nanite_enabled':nanite,'before':old,'after':new,'source':json.loads((D/'source-manifest.json').read_text()),'actor_count':len(after),'saved_reopened':True,'all_other_actor_scoped_properties_unchanged':True};(D/'native-patch-manifest.json').write_text(json.dumps(proof,indent=2));print('SUPPORT_READONLY_VALIDATED',proof['sha256'])
