from production_common import *
import re
D=R/'madmapper_highlight_H04/deliverables';OLD=R/'madmapper_highlight_H03/world_clipped/deliverables';S=8192;arr=cache_arrays(100,S);ids=np.asarray(Image.open(H02/'assembly_1_100/Highlight_Stop_IDs_uint8.png'));fire=np.asarray(Image.open(R/'madmapper_hybrid_UV02/deliverables/Fireplace_New_Chart_Mask_8192.png'))>0;rows=[]
for sid,(title,body) in enumerate(COPY['spaces'],1):
    slug=re.sub(r'[^A-Za-z0-9]+','_',title).strip('_');folder=D/slug;q=json.loads((folder/'Pagination_QA.json').read_text());a=np.asarray(Image.open(OLD/q['highlight_mask']));rgb=np.asarray(Image.open(folder/q['pages'][0]['atlas']).convert('RGB'));c=np.array(q['colour_RGB'],float);dominant=int(np.argmax(c));tested=0;raisedcount=0;missed=0;leaked=0;residual=0.;raisedmax=0.;floorvalues=[];raisedvalues=[]
    for y0 in range(0,S,256):
        sl=np.s_[y0:min(S,y0+256),:];x=arr['x'][sl]/64.;y=arr['y'][sl]/64.;z=arr['z'][sl]/64.;valid=arr['valid'][sl]>0;up=arr['up'][sl]>0;gym=(ids[sl]==13)&valid&up&(z<6);caption=gym&(x>=235)&(x<=448)&(y>=231)&(y<=451);allow=~(caption if sid==13 else gym)&~fire[sl];active=(a[sl]>=32)&valid&allow;pixels=rgb[sl];nz=np.any(pixels,axis=2)
        missed+=int((active&~nz).sum());leaked+=int(((a[sl]==0)&allow&nz).sum());tested+=int(active.sum());fixture=active&(z>=5.8);raisedcount+=int(fixture.sum())
        if active.any():residual=max(residual,float(np.abs(pixels.astype(float)-pixels[:,:,dominant,None]/255*c)[active].max()))
        full=active&(a[sl]==255);level=pixels[:,:,dominant]/255.;fixturefull=full&(z>=5.8)
        if fixturefull.any():raisedmax=max(raisedmax,float(level[fixturefull].max()));raisedvalues.extend(level[fixturefull].tolist())
        floor=full&up&(z<5.8)
        if floor.any():floorvalues.extend(level[floor].tolist())
    assert tested>0 and missed==0 and leaked==0,(title,tested,missed,leaked)
    assert residual<=1.01 and raisedmax<=.72+1/255,(title,residual,raisedmax)
    row={'title':title,'stop_id_metadata_only':f'HS{sid:02d}','actual_atlas_sampled':q['pages'][0]['atlas'],'sampled_selected_opaque_receiver_texels':tested,'sampled_raised_fixture_and_wall_texels':raisedcount,'missing_lit_receiver_texels_at_alpha_ge32':missed,'nonzero_texels_outside_inherited_H03_alpha_excluding_gym_caption_backdrop_and_fireplace':leaked,'actual_same_hue_max_RGB_byte_residual':residual,'maximum_full_coverage_raised_surface_fraction_of_room_colour_peak':raisedmax,'raised_surface_fraction_median':float(np.median(raisedvalues)) if raisedvalues else None,'floor_surface_fraction_median':float(np.median(floorvalues)) if floorvalues else None,'all_pages_share_identical_room_and_fixture_treatment':True,'fireplace_chart_nonzero_texels':int(np.any(rgb[fire],axis=1).sum()),'fireplace_on':sid==3,'mask_sha256':sha(OLD/q['highlight_mask'])};assert bool(row['fireplace_chart_nonzero_texels'])==(sid==3);rows.append(row);print('ACTUAL H04 RECEIVER COLOUR/COVERAGE PASS',title,tested,raisedcount,residual,flush=True)
out={'status':'PASS: actual standalone atlas pixels preserve same room hue, dim raised surfaces, H03 alpha edges and Commons-only fireplace','stops':13,'colour_residual_tolerance_RGB_byte':1.01,'test_scope':'Sample actual original opaque world-coordinate cache at inherited full-receiver H03 alpha coverage>=32; exclude exact gym captions (all gym backdrop for nonGym stops) and separate appended fireplace charts. All pages have identical base transfer; page overlays separately verified against H03. AA quantisation may eliminate very low alpha texels; no stronger covered surface is dark. Raisedz>=5.8mm includes all selected furniture and wall surfaces.','rows':rows,'geometry_UVs_world_scale_origin_changed':False,'inherited_reference_boundary_limit':'H03 registered reference regions reused; no fresh R29 semantic room-perimeter audit claimed.','physical_projection_or_readability_verified':False};(D/'Actual_Surface_Colour_And_Coverage_QA.json').write_text(json.dumps(out,indent=2));print('ACTUAL13 H04 SURFACE AUDIT COMPLETE',flush=True)
