from pathlib import Path
import json,hashlib,datetime,shutil
r=Path(__file__).resolve().parent;p=r.parent/'CampusCenter-vive/unreal/unreal_project';a=r.parent/'CampusCenter-vive/review_build_vive_openxr_r07_r01/Windows';load=lambda n:json.loads((r/n).read_text())
def digest(path):
 h=hashlib.sha256()
 with path.open('rb') as stream:
  for chunk in iter(lambda:stream.read(8*1024*1024),b''):h.update(chunk)
 return h.hexdigest()
normal=load('packaged-normal/process-result.json');assert normal['exit_code']==0 and normal['elapsed_seconds']>=300 and load('package-final.json')['exit_code']==0
assert load('input-validation.json')['passed'] and len(load('input-validation.json')['tests'])==26 and load('keyboard-validation.json')['passed'] and load('preservation.json')['status']=='passed'
logs=[r/'packaged-normal/runtime.log',r/'packaged-images/Cases/runtime.log'];fail=[];xr=[];perf=[]
for log in logs:
 lines=log.read_text(errors='replace').splitlines();fail.extend({'file':str(log),'line':l} for l in lines if any(x in l for x in ['Default Material will be used','Failed to compile Material','Missing cached shadermap','was not cooked','Fatal error','Assertion failed','Nanite usage']))
 xr.extend(l for l in lines if any(x in l for x in ['Mounting Engine plugin OpenXR','Mounting Engine plugin XRBase','OpenXRHMDModule::InitInstance','xrEnumerateInstanceExtensionProperties failed','Failed to enumerate extensions','CampusViveXR:']))
 perf.append({'file':str(log),'pso_creation_hitch_reports':[l for l in lines if 'pso creation hitch' in l.lower()],'audio_underrun_lines':sum('underrun' in l.lower() and 'audio' in l.lower() for l in lines)})
assert not fail;assert any('Mounting Engine plugin OpenXR' in l for l in xr);assert any('trigger mapping registered before XR action creation=true' in l for l in xr);assert any('xrEnumerateInstanceExtensionProperties failed' in l for l in xr)
loader=a/'Engine/Binaries/ThirdParty/OpenXR/win64/openxr_loader.dll';assert loader.exists();runtime={'status':'software/plugin/configuration checks passed; actual XR session blocked by missing runtime','runtime_material_or_fatal_warnings':fail,'XR_log_evidence':xr,'OpenXR_loader':{'file':str(loader),'sha256':digest(loader)},'performance':perf,'headset_operation':'unverified','runtime_session_created':False,'system_changes':False};(r/'runtime-validation.json').write_text(json.dumps(runtime,indent=2))
source=load('control-source-manifest.json');assert digest(Path(source['source_archive']))==source['archive_sha256'];assert all(digest(p/x['project_relative_path'])==x['sha256'] for x in source['files'])
old= json.loads((r.parent/'vr-trigger-walk-r01/frozen-review-archive.json').read_text());oldroot=Path(old['archive']);assert all(digest(oldroot/x['file'])==x['sha256'] for x in old['files']);(r/'rollback-package-check.json').write_text(json.dumps({'R06_archive_files_verified':len(old['files']),'unchanged':True},indent=2))
saved=a/'CampusCenter/Saved';dest=r/'packaged-generated-saved-state'
if saved.exists():assert not dest.exists() and saved.resolve().is_relative_to(r.parent.resolve());shutil.move(str(saved),str(dest))
launcher=a/'Review_CampusCenter_Vive_R07_OpenXR.cmd';assert not launcher.exists();launcher.write_text('@echo off\ncd /d "%~dp0"\nstart "" "%~dp0CampusCenter\\Binaries\\Win64\\CampusCenter.exe" '+source['map']+' -DisablePlugins=MetaHumanCrowdContent -game -vr -fullscreen -ResX=1920 -ResY=1080 -ExecCmds="r.ScreenPercentage 50,stat fps" -nosplash\n')
(a/'NOTICES.txt').write_text('Private R07 OpenXR/SteamVR-targeted review. Use Review_CampusCenter_Vive_R07_OpenXR.cmd to select the revised map and request VR. Installed UE OpenXR activated locally; controller context registered for XR actions; map-only Local tracking origin for elevated first-person camera. Retained movement/rendering/input settings. Real SteamVR runtime is absent on the build machine and no actual XR session/headset test succeeded; runtime installation/selection and hardware acceptance require follow-up authorization. No OS/runtime installation or active-runtime changes. Original R06 archive remains preserved.\n')
archive={'frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'archive':str(a),'map':load('frozen-final.json'),'files':[{'file':x.relative_to(a).as_posix(),'bytes':x.stat().st_size,'sha256':digest(x)} for x in sorted(a.rglob('*')) if x.is_file()]};(r/'frozen-review-archive.json').write_text(json.dumps(archive,indent=2))
names=['control-source-manifest.json','frozen-review-archive.json','package-final.json','map-created.json','preservation.json','protected-source-validation.json','diagnostic-gate-check.json','input-validation.json','keyboard-validation.json','runtime-availability.json','runtime-validation.json','rollback-package-check.json','packaged-normal/process-result.json','packaged-images/Cases/result.json']
report={'status':'XR-configured package and nonhardware checks complete; live SteamVR session/hardware acceptance blocked','completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'map':source['map'],'map_sha256':load('frozen-final.json')['map_sha256'],'archive':str(a),'launcher':str(launcher),'source_manifest':str(r/'control-source-manifest.json'),'build_cook_stage_archive_exit':0,'VR_requested_normal_run_seconds':normal['elapsed_seconds'],'normal_window_close_exit':0,'runtime_session_created':False,'input_cases_passed':26,'keyboard_cases_passed':5,'baseline_actors_accounted':2232,'final_actor_count':2233,'configuration_exceptions':'OpenXR project activation; pre-session EnhancedInput context registration. XRBase dependency automatic; map-only Local tracking origin and -vr launcher. Other settings preserved.','runtime_blocker':'No SteamVR in four registered Steam libraries; HKLM/HKCU OpenXR ActiveRuntime missing; XR_RUNTIME_JSON unset. Packaged OpenXR loader reports extension enumeration failure due to no runtime. No installation/global selection performed.','headset_operation':'unverified; hardware/session/controller/performance/comfort acceptance pending','publication':'No independent push; parent publication hold until scoped readiness decision.','evidence':[{'file':name,'sha256':digest(r/name)} for name in names]}
(r/'final-control-handoff.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
