from pathlib import Path
import json,hashlib,datetime,zipfile
r=Path(__file__).parent;p=r.parent/'CampusCenter-vive/unreal/unreal_project';names=['CampusCenter.uproject','Config/DefaultInput.ini','Plugins/CampusCrowdFix/CampusCrowdFix.uplugin','Plugins/CampusCrowdFix/Source/CampusCrowdFix/CampusCrowdFix.Build.cs','Content/Campus/Maps/CampusCenter_Vive_EQ27_R07_OpenXR.umap']
names += ['Plugins/CampusCrowdFix/Source/CampusCrowdFix/'+folder+'/'+name+ext for folder,ext in [('Public','.h'),('Private','.cpp')] for name in ['CampusViveTriggerWalk','CampusViveXROrigin']]
names += ['Content/Campus/ViveTriggerWalkR01/'+name+'.uasset' for name in ['IA_TriggerWalk_Left','IA_TriggerWalk_Right','IMC_ViveTriggerWalk']]
archive=r/'CampusCenter_Vive_OpenXR_R07_Source.zip';assert not archive.exists();rows=[]
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
 for name in names:
  data=(p/name).read_bytes();rows.append({'project_relative_path':name,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()});z.writestr(name,data)
engine=Path(r'C:/Program Files/Epic Games/UE_5.8/Engine');provenance=[]
for name in ['Plugins/Runtime/OpenXR/OpenXR.uplugin','Plugins/Runtime/XRBase/XRBase.uplugin','Plugins/Runtime/OpenXR/Source/OpenXRInput/Private/OpenXRInput.cpp','Plugins/EnhancedInput/Source/EnhancedInput/Public/EnhancedInputDeveloperSettings.h']:
 provenance.append({'installed_engine_file':str(engine/name),'sha256':hashlib.sha256((engine/name).read_bytes()).hexdigest()})
report={'frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline_git_branch':'codex/vr','baseline_git_commit':'db5b1cec11adbdf25b2df4e1615d00d5f009fc82','baseline_map':'/Game/Campus/Maps/CampusCenter_Vive_EQ27_R06_TriggerWalk','map':'/Game/Campus/Maps/CampusCenter_Vive_EQ27_R07_OpenXR','source_archive':str(archive.resolve()),'archive_sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'files':rows,'OpenXR_activation':'Installed Epic OpenXR enabled; XRBase and EnhancedInput dependencies automatic. No legacy SteamVR plugin in installed UE runtime folder.','binding_registration':'DefaultMappingContexts includes existing trigger context with bAddImmediately=False; registered for OpenXR actions before session, activated only by trigger helper in the review map.','controller_bindings':{'profile':'/interaction_profiles/htc/vive_controller','left_axis':'/user/hand/left/input/trigger/value','left_click':'/user/hand/left/input/trigger/click','right_axis':'/user/hand/right/input/trigger/value','right_click':'/user/hand/right/input/trigger/click','action_semantics':'Separate per-hand Axis1D highest-absolute-value actions; one horizontal camera-yaw movement request per frame; existing speed/collision/turning retained; release/focus/tracking safety latch.'},'pawn_contract':'Retained BP_FirstPersonCharacter, HMD-locked elevated camera; R07-only origin helper selects application Local tracking origin when OpenXR provider exists. No floor-height guess, recenter, world-scale, rendering or movement change.','launch_contract':'Use new R07 launcher selecting map and adding -vr. Original default map retained for rollback; raw exe default is not the R07 review entry.','nonhardware_tests':'26 raw-key/OpenXR-style EnhancedInput injection cases plus 5 keyboard coexistence cases passed. No actual XR session/controller/headset certification.','runtime_blocker':'SteamVR absent from four registered Steam libraries; no active OpenXR registry runtime or environment override. OS/software changes are outside this authorization.','required_followup':'Authorized SteamVR installation/active OpenXR runtime selection and real Vive tracking/controller, height, collision, performance and comfort acceptance on hardware.','installed_source_provenance':provenance,'official_sources':['https://dev.epicgames.com/documentation/unreal-engine/developing-for-steamvr-in-unreal-engine?lang=en-US','https://dev.epicgames.com/documentation/unreal-engine/openxr-input-in-unreal-engine','https://dev.epicgames.com/documentation/unreal-engine/developing-for-headmounted-experiences-with-openxr-in-unreal-engine?lang=en-US'],'publication':'Parent publisher holds final publication pending the scoped XR/runtime readiness decision. No independent push.'}
(r/'control-source-manifest.json').write_text(json.dumps(report,indent=2));print(archive,report['archive_sha256'])
