const $=s=>document.querySelector(s),canvas=$('#projection'),ctx=canvas.getContext('2d',{alpha:false}),W=1024,H=786;
const scratch=document.createElement('canvas');scratch.width=W;scratch.height=H;const g=scratch.getContext('2d');
const status=$('#status'),diag=$('#diagnostics');let map,walk,ids,valid,base,ink,align,mask,highlight,player,room=-1,mode='game',paused=false,loaded=false,last=0,auto=[],visited=new Set(),heading=0,keys=new Set(),video=null,moves=0,blocked=0;
let speed=40;
const illustrations=new Map(),videoCache=new Map();
async function image(src){const im=new Image();im.src=src;await im.decode();return im}
function pixels(im){const c=document.createElement('canvas');c.width=W;c.height=H;const q=c.getContext('2d');q.drawImage(im,0,0);return q.getImageData(0,0,W,H).data}
function channel(im){const p=pixels(im),out=new Uint8Array(W*H);for(let i=0;i<out.length;i++)out[i]=p[i*4];return out}
function can(x,y){x=Math.round(x);y=Math.round(y);return x>=0&&y>=0&&x<W&&y<H&&walk[y*W+x]>0}
function roomAt(x,y){return ids[Math.round(y)*W+Math.round(x)]-1}
function enter(){const n=roomAt(player.x,player.y);if(n===room||n<0)return;room=n;visited.add(room);const r=map.rooms[room];highlight=document.createElement('canvas');highlight.width=W;highlight.height=H;const hg=highlight.getContext('2d'),im=hg.createImageData(W,H);for(let i=0;i<W*H;i++){if(ids[i]===room+1&&valid[i]){im.data[i*4]=37;im.data[i*4+1]=209;im.data[i*4+2]=177;im.data[i*4+3]=140}}hg.putImageData(im,0,0);updateStatus()}
function updateStatus(){if(!loaded)return;const r=map.rooms[Math.max(room,0)];status.textContent=`${r.number} · ${r.name}\nVisited ${visited.size} / 30 connected areas\nPosition ${player.x.toFixed(1)}, ${player.y.toFixed(1)}${auto.length?' · following route':''}${paused?' · paused':''}`}
function stepOnce(dx,dy){let did=false;if(can(player.x+dx,player.y)){player.x+=dx;did=true}else if(Math.abs(dx)>.001)blocked++;if(can(player.x,player.y+dy)){player.y+=dy;did=true}else if(Math.abs(dy)>.001)blocked++;if(did&&(dx||dy)){heading=Math.atan2(dy,dx);moves++;enter()}updateStatus()}
function step(dx,dy){const count=Math.max(1,Math.ceil(Math.hypot(dx,dy)/.5));for(let i=0;i<count;i++)stepOnce(dx/count,dy/count)}
function reset(){player={x:map.start[0],y:map.start[1]};room=-1;visited.clear();auto=[];keys.clear();enter();canvas.focus();updateStatus()}
function pathTo(target){const sx=Math.round(player.x),sy=Math.round(player.y),start=sy*W+sx,goal=target[1]*W+target[0];const previous=new Int32Array(W*H);previous.fill(-1);const queue=new Int32Array(W*H);let head=0,tail=0;queue[tail++]=start;previous[start]=start;
 while(head<tail&&previous[goal]===-1){const p=queue[head++],x=p%W,y=Math.floor(p/W);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,k=yy*W+xx;if(xx>=0&&xx<W&&yy>=0&&yy<H&&walk[k]&&previous[k]===-1){previous[k]=p;queue[tail++]=k}}}
 if(previous[goal]===-1)return[];let p=goal,result=[];while(p!==start){result.push({x:p%W,y:Math.floor(p/W)});p=previous[p]}return result.reverse()}
function route(){const i=Number($('#destination').value);if($('#destination').value===''||!map.rooms[i].visit_xy)return;setMode('game');auto=pathTo(map.rooms[i].visit_xy);canvas.focus();updateStatus()}
function wrapText(text,x,y,width,size){g.font=`600 ${size}px system-ui`;while(g.measureText(text).width>width&&size>8){size--;g.font=`600 ${size}px system-ui`}g.fillText(text,x,y)}
function gymPanel(){const r=map.rooms[Math.max(room,0)],[x,y,w,h]=map.gym_panel;g.fillStyle='#091820';g.fillRect(x,y,w,h);g.strokeStyle='#5bd5bd';g.lineWidth=1;g.strokeRect(x+.5,y+.5,w-1,h-1);g.fillStyle='#91d8ca';g.font='10px system-ui';g.fillText('KING SCHOOL  /  DISCOVER THE CAMPUS',x+12,y+17);g.fillStyle='#edf7f8';wrapText(`${r.number}  ${r.name}`,x+12,y+35,w-24,15);const im=illustrations.get(r.number);if(im){const iw=w-16,ih=h-66,scale=Math.min(iw/im.width,ih/im.height),dw=im.width*scale,dh=im.height*scale;g.drawImage(im,x+(w-dw)/2,y+46+(ih-dh)/2,dw,dh)}g.fillStyle='#92abba';g.font='9px system-ui';wrapText(r.image_caption,x+12,y+h-9,w-24,9)}
function draw(t){g.clearRect(0,0,W,H);if(mode==='game'){g.drawImage(base,0,0);if(highlight){g.globalAlpha=.35+.1*Math.sin(t*.002);g.drawImage(highlight,0,0);g.globalAlpha=1}if(auto.length){g.strokeStyle='#4d837e';g.lineWidth=1;g.beginPath();g.moveTo(player.x,player.y);for(let i=0;i<auto.length;i+=3)g.lineTo(auto[i].x,auto[i].y);g.stroke()}gymPanel();g.save();g.translate(player.x,player.y);g.rotate(heading);g.fillStyle='rgba(0,0,0,.4)';g.beginPath();g.ellipse(1,1,5,4,0,0,Math.PI*2);g.fill();g.fillStyle='#76e5cc';g.fillRect(-2,-4,4,8);g.fillStyle='#f1f8f2';g.beginPath();g.arc(1.5,0,2.7,0,Math.PI*2);g.fill();g.restore()}else if(mode==='alignment')g.drawImage(align,0,0);else if(mode==='ink')g.drawImage(ink,0,0);else if(video&&video.readyState>=2)g.drawImage(video,0,0,W,H);
 g.globalCompositeOperation='destination-in';g.drawImage(mask,0,0);g.globalCompositeOperation='source-over';ctx.fillStyle='#000';ctx.fillRect(0,0,W,H);ctx.drawImage(scratch,0,0);}
function tick(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;if(loaded&&!paused&&mode==='game'){let dx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),dy=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);if(dx||dy){auto=[];const mag=Math.hypot(dx,dy);step(dx/mag*speed*dt,dy/mag*speed*dt)}else if(auto.length){let remaining=speed*dt;while(auto.length&&remaining>0){const p=auto[0],dx=p.x-player.x,dy=p.y-player.y,len=Math.hypot(dx,dy);if(len<.001){auto.shift();continue}const advance=Math.min(remaining,len);step(dx/len*advance,dy/len*advance);remaining-=advance;if(advance===len)auto.shift();else break}}}if(loaded){updateStatus();draw(paused?0:t)};requestAnimationFrame(tick)}
const titles={game:['Explore the campus','Walk through the modeled doorways. Enter a room to light it up and display a cinematic ImageGen reference on the gym floor.'],ink:['An ink-drawn campus','An original interpretation with irregular grid lines, hatched edges and furniture outlines registered to the actual print.'],alignment:['Align the projector','Match the 25 mm grid, numbered targets, green edges and amber furniture tops. Walls and clear panes remain black.'],Depth_Contours:['Height contours','Moving contours follow modeled surface height and distance from edges. Furniture has a different phase from the floor.'],Surface_Ripples:['Surface ripples','Concentric light bands use a three-dimensional distance field, bending their phase over raised furniture.'],Architecture_Scan:['Architecture scan','A moving light field responds to elevation and surface orientation, revealing the geometry without changing sunlight.']};
async function setMode(m){mode=m;auto=[];keys.clear();if(video)video.pause();video=null;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#modeTitle').textContent=titles[m][0];$('#description').textContent=titles[m][1];if(!['game','ink','alignment'].includes(m)){if(!videoCache.has(m)){const v=document.createElement('video');v.src=`examples/${m}_Browser.mp4`;v.loop=true;v.muted=true;v.playsInline=true;videoCache.set(m,v)}video=videoCache.get(m);if(!paused)await video.play()}canvas.focus()}
function pause(){paused=!paused;$('#pause').textContent=paused?'Resume':'Pause';if(video){if(paused)video.pause();else video.play()}updateStatus()}
async function fullscreen(){if(!document.fullscreenElement)await canvas.requestFullscreen();else await document.exitFullscreen();canvas.focus()}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#fullscreen').onclick=fullscreen;$('#pause').onclick=pause;$('#reset').onclick=reset;$('#route').onclick=route;
window.addEventListener('keydown',e=>{if(!loaded||e.target.tagName==='SELECT')return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(k)){e.preventDefault();keys.add(k);auto=[];if(!e.repeat&&mode==='game'&&!paused){const dx=(k==='d'||k==='ArrowRight'?1:k==='a'||k==='ArrowLeft'?-1:0),dy=(k==='s'||k==='ArrowDown'?1:k==='w'||k==='ArrowUp'?-1:0);step(dx*speed*.04,dy*speed*.04)}}if(k==='r')reset();if(k==='f')fullscreen();if(k===' '){e.preventDefault();if(!e.repeat)pause()}});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>keys.clear());canvas.onclick=()=>canvas.focus();
$('#test').onclick=()=>{let leaks=0;const p=ctx.getImageData(0,0,W,H).data;for(let i=0;i<valid.length;i++)if(!valid[i]&&(p[i*4]||p[i*4+1]||p[i*4+2]))leaks++;let reachable=0;for(const r of map.rooms)if(r.visit_xy&&pathTo(r.visit_xy).length)reachable++;diag.textContent=`Assets: ${illustrations.size}/31 cinematic assignments\nBlackout: ${leaks===0?'PASS':'FAIL '+leaks}\nAvatar on walkable floor: ${can(player.x,player.y)?'PASS':'FAIL'}\nRoom routes: ${reachable} found (current tile can be zero length)\nMovement updates: ${moves}; blocked wall steps: ${blocked}\nSpeed: ${speed/20}× original (${speed} px/s)\nCanvas: ${canvas.width} × ${canvas.height}`;};
$('#speed').onchange=()=>{speed=Number($('#speed').value);canvas.focus();updateStatus()};
try{map=await(await fetch('map.json')).json();speed=map.speed_px_per_second;$('#speed').value=String(speed);[base,ink,align]=await Promise.all(['Explorer_Base.png','Ink_Map.png','Alignment_25mm.png'].map(n=>image('assets/'+n)));const [wi,ri,vi]=await Promise.all(['walkable.png','room_ids.png','receiver.png'].map(n=>image('assets/'+n)));walk=channel(wi);ids=channel(ri);valid=channel(vi);mask=document.createElement('canvas');mask.width=W;mask.height=H;const mg=mask.getContext('2d'),mp=mg.createImageData(W,H);for(let i=0;i<valid.length;i++){mp.data[i*4]=mp.data[i*4+1]=mp.data[i*4+2]=255;mp.data[i*4+3]=valid[i]?255:0}mg.putImageData(mp,0,0);for(let i=0;i<map.rooms.length;i++){const r=map.rooms[i],o=document.createElement('option');o.value=i;o.textContent=`${r.number} · ${r.name}${r.visit_xy?'':' (no modeled connecting doorway)'}`;o.disabled=!r.visit_xy;$('#destination').append(o)}await Promise.all(map.rooms.map(async r=>{illustrations.set(r.number,await image(r.image))}));loaded=true;reset();requestAnimationFrame(tick)}catch(e){status.textContent='Unable to load: '+e.message;console.error(e)}
