import os,shutil
from pathlib import Path
import json,subprocess,hashlib
R=Path(__file__).parent;T=R/'madmapper_ripple_R04/whole_model';D=T/'deliverables';S=T/'Lossless_Atlas_Sequence_4096';qfile=D/'Thin_Black_Staggered_Transfer_QA.json';q=json.loads(qfile.read_text());FRAMES=q['frames'];assert FRAMES==880
ff=Path(os.environ.get('FFMPEG',shutil.which('ffmpeg') or 'ffmpeg'));target=D/'Ripple_R04_Black_Thin_Staggered_Connected_UV02_1_100_4096_Lossless_PNG.mov';assert not target.exists()
subprocess.run([str(ff),'-hide_banner','-loglevel','error','-framerate','20','-i',str(S/'frame_%04d.png'),'-frames:v',str(FRAMES),'-c:v','copy',str(target)],check=True)
probe=json.loads(subprocess.check_output([str(Path(os.environ.get('FFPROBE',shutil.which('ffprobe') or 'ffprobe'))),'-v','error','-count_frames','-select_streams','v:0','-show_entries','stream=codec_name,width,height,r_frame_rate,nb_read_frames,duration','-of','json',str(target)]));stream=probe['streams'][0];assert stream['codec_name']=='png' and int(stream['nb_read_frames'])==FRAMES and abs(float(stream['duration'])-44)<.001
packets=json.loads(subprocess.check_output([str(Path(os.environ.get('FFPROBE',shutil.which('ffprobe') or 'ffprobe'))),'-v','error','-select_streams','v:0','-show_packets','-show_data_hash','sha256','-show_entries','packet=pts_time,size,data_hash','-of','json',str(target)]))['packets'];assert len(packets)==FRAMES;rows=[]
for frame,p in enumerate(packets):
    source=S/f'frame_{frame:04d}.png';h=hashlib.sha256(source.read_bytes()).hexdigest();assert p['data_hash'].split(':')[-1].lower()==h and int(p['size'])==source.stat().st_size
    rows.append({'frame':frame,'PNG_packet_identical_to_source_file':True,'PNG_source_sha256':h,'packet_bytes':int(p['size'])})
subprocess.run([str(ff),'-hide_banner','-loglevel','error','-i',str(target),'-f','null','-'],check=True)
qa={'status':'PASS: all880 raw atlas frames decode; every PNG video packet byte-identical to corresponding exact-black lossless source','file':str(target),'bytes':target.stat().st_size,'sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'codec':'PNG in QuickTime MOV, original PNG bitstreams copied without reencoding','resolution':[4096,4096],'fps':20,'frames':FRAMES,'duration_seconds':44,'all_frames_decoded':True,'all880_PNG_packets_match_lossless_source_SHA_and_size':True,'background_RGB_lossless_exact':[0,0,0],'first_last_source_and_movie_packets_exact_black':True,'source_sequence':str(S),'packet_checks':rows,'preview_is_matching_same_source_frame_sequence':q['file'],'receiver_OBJ_sha256':q['receiver_OBJ_sha256'],'geometry_UVs_registration_and_R03_changed':False,'physical_projection_or_MadMapper_playback_verified':False}
(D/'Lossless_Atlas_Movie_QA.json').write_text(json.dumps(qa,indent=2));q['matching_primary_atlas_movie_pending']=False;q['matching_primary_atlas_movie']=str(target);q['matching_primary_atlas_SHA256']=qa['sha256'];q['lossless_black_atlas_movie_QA']='Lossless_Atlas_Movie_QA.json';qfile.write_text(json.dumps(q,indent=2));print(json.dumps({k:qa[k] for k in ['status','file','bytes','sha256']},indent=2),flush=True)
