import unreal,pathlib,json
root=pathlib.Path(unreal.Paths.project_dir());levels=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
levels.load_level('/Game/Campus/Maps/Campus_GuidedTour')
actors=unreal.get_editor_subsystem(unreal.EditorActorSubsystem).get_all_level_actors()
tour=next(a for a in actors if isinstance(a,unreal.LevelSequenceActor))
camera=next(a for a in actors if a.get_actor_label()=='Guided_Tour_Camera')
seq=tour.get_sequence();bid=unreal.MovieSceneObjectBindingID();bid.set_editor_property('guid',seq.get_bindings()[0].get_id())
entry=unreal.MovieSceneBindingOverrideData()
entry.set_editor_property('object_binding_id',bid)
entry.set_editor_property('object',camera)
entry.set_editor_property('overrides_default',True)
tour.get_editor_property('binding_overrides').set_editor_property('binding_data',[entry])
assert levels.save_current_level()
(root/'tour_binding_fix.json').write_text(json.dumps({'binding':str(seq.get_bindings()[0].get_id()),'camera':camera.get_path_name(),'reason':'Bind cloned tour map camera explicitly instead of resolving the source-map actor path'}))
