import json,pathlib,hashlib,shutil
root=pathlib.Path(__file__).parent;out=root/'art_batch_v26_r01';m=json.loads((out/'manifest.json').read_text())
assert all(e['matches_manifest'] for p in m['existing_packages'] for e in p['entries'])
for a in m['artworks']:
 if a['source']=='IMG_6988.jpeg':a['normalization'].update({'container':'MPO','included_frame':0,'excluded_frame':1,'excluded_frame_role':'grayscale auxiliary; not separate artwork'})
m['material_mapping']={'ART26_Frame_MatteCharcoal':{'base_color_srgb':[.025,.025,.025],'roughness':.75,'metallic':0},'ART26_IMG_*_Photo':{'base_color_texture':'matching artwork texture field','srgb':True,'roughness':1,'metallic':0,'two_sided':False,'opacity_mode':'opaque'}}
m['import_contract']={'asset_root':'/Game/Campus/ArtworkART26R01','formats':'FBX primary static meshes; GLB portable embedded-texture alternate. Import one format per ID, never both.','fbx_units':'FBX declares metre scene units; Unreal converts to centimetres, import uniform scale 1. Validate dimensions against manifest.','actor_tags':['ART26_R01','stable_id'],'idempotence':'Upsert by stable_id tag inside new enhancement map only. Skip duplicate IDs already present; do not delete pre-existing student art actors.','map_policy':'Use current worker-owned enhancement map; this package loads no obsolete map.','textures':'Import textures with sRGB enabled, use artwork texture mapping for Photo material; GLB embeds texture.','collision':'No collision for wall presentation meshes. Do not import QA_ONLY context objects.','placement_gate':'Before spawning, verify all four artwork corners against current support wall and compare door/equipment/window/furniture clearances; reject unsupported placements. The absolute transforms are proposed anchors, not unconditional spawn instructions.'}
m['render_contract']['samples']='EEVEE defaults; sample count was not explicitly set in builder. Saved scene provides authoritative settings.'
assert len(list((out/'renders').glob('*.png')))==12
import struct
for p in (out/'renders').glob('*.png'):
 assert struct.unpack('>II',p.read_bytes()[16:24])==(640,640)
(out/'manifest.json').write_text(json.dumps(m,indent=2))
for f in ['prepare_art.py','normalize_art.ps1','build_art.py','validate_art.py','finish_art.py']:shutil.copy2(root/f,out/'source'/f)
(out/'HANDOFF.txt').write_text('CampusCenter ART26_R01 — separate Tank output\n\n11 unique source-photo presentations; 12 originals verified before/after. IMG_1795 aliases IMG_1869 and is not instantiated. MPO uses primary RGB artwork; EXIF orientation baked with embedded color management. No AI regeneration, cropping, inpainting, or invented artwork.\n\nEditable scene: source/CampusCenter_Art26_R01.blend\nImport contract and deterministic proposed anchors: manifest.json\nPer-asset FBX and texture mapping plus embedded-texture GLB alternative: exports/ and textures/\nVisual evidence: renders/ (11 asset stills and proposed_layout.png); validation.json includes export reopening tests.\n\nThese are photo presentations of sculptures/garments, labeled estimated/incomplete reconstruction. Volumetric replicas are not delivered. This preserves visible source appearance and follows the inventory photo-first option. Old v02 textures were re-verified and retained by reference; no duplicate old assets created.\n\nPlacement is intentionally conditional on current worker map traces and furniture clearance checks. Layout render is an art-only inventory-derived wall/floor schematic, not a furnished v26 room approval. No UE session or print model was changed. Original photos, frozen baselines, primary worker scene/maps and Vive files remain untouched.\n\nBlender background used two CPU threads; no other processes stopped. Runtime/import/desktop/Vive checks remain with integration owner.\n')
files={str(p.relative_to(out)).replace('\\','/'):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(out.rglob('*')) if p.is_file() and p.name not in ['SHA256SUMS.json'] and p.suffix not in ['.blend1']}
(out/'SHA256SUMS.json').write_text(json.dumps(files,indent=2));print('MANIFEST_SHA256',files['manifest.json']);print('BLEND_SHA256',files['source/CampusCenter_Art26_R01.blend'])
