from pathlib import Path
import json,hashlib
R=Path(__file__).parent/'combined_r01';N=R/'native-preview';s=(N/'review.html').read_text();s=s.replace('CampusCenter R24 actual Unreal review','CampusCenter R25 actual Unreal review').replace('<h1>CampusCenter desktop R24</h1>','<h1>CampusCenter desktop R25</h1><p>Final R25 corrects the two trophy collision profiles to explicit NoCollision and verifies 2,231 actors. All 39 asset files, actor transforms, geometry and materials match the rendered R24 state. The final R25 screen and hall-clearance images below were captured after this correction.</p>').replace('R24_BSOD.png','R25_Reception_BSOD.png').replace('R24_Cases_Final.png','R25_CaseHall_Clearance.png');(N/'review-r25.html').write_text(s,encoding='utf-8')
proof=json.loads((R/'packaged-smoke-proof.json').read_text());assert proof['game_alive_before_end'] and proof['elapsed_seconds']>60;identity=json.loads((R/'shared-consumer-handoff-r25-r02-identity.json').read_text());assert hashlib.sha256((R/identity['archive']).read_bytes()).hexdigest()==identity['sha256'];status={'map':identity['map'],'actor_count':2231,'desktop_archive':'desktop_review_r25/Windows','entrypoint':'desktop_review_r25/Windows/CampusCenter.exe','default_entrypoint_verified':True,'cook_exit_code':0,'uat_stage_archive_exit_code':0,'trophy_no_collision_saved_verified':True,'baseline_case_footprints_preserved':True,'case_hall_walks_before_after_pass':True,'paired_14_probe_regressions':[],'two_inherited_failures':['Research113_25','Fitness_RackFront_Aisle'],'native_material_binding_verified_after_reload':True,'new_cooked_packages_portable':40,'packaged_smoke':proof,'consumer_handoff':identity,'published':False,'warm_run_performance_certified':False,'cook_warning_scope':'Legacy incremental + unversioned warning; no C++ serialization changes; R25 new map fully recooked. Inherited SM5 volume shader fallback warnings in full cook; packaged primary PCD3D_SM6 ran without fatal/asset loading errors.'};(R/'build-status-r25.json').write_text(json.dumps(status,indent=2))
receipts={'bsod':{'library_file_id':'libfile_654a61cba0f08191a16a24d97b352599','file_id':'file_00000000ef6081fb87678c5e87cec75a'},'clearance':{'library_file_id':'libfile_b14d12260b848191b8c0d2d7a539b1a6','file_id':'file_00000000572481fb9e7d96b9bbd0a26a'},'delta':{'library_file_id':'libfile_2f77e09742fc819186a927d4d8f85e08','file_id':'file_00000000fc0481fb8b0db6523ebd68a1'},'equipment_comparison':{'library_file_id':'libfile_75c0b83d52e081919704fe8460bc86aa','file_id':'file_000000003f6881fb8cc68a2859fa2b97'},'metadata_note':'Windows lacks os.setxattr; complete retained file identities in this receipt. Private Library saves only; no publishing/sharing actions.'};(R/'library-receipts-r25.json').write_text(json.dumps(receipts,indent=2))
(R/'README_R25.md').write_text('''# CampusCenter desktop R25 — complete, unpublished

Open `desktop_review_r25/Windows/CampusCenter.exe`. Its portable generated bootstrap selects R25 automatically. Keep its CampusCenter and Engine folders beside it. The first-person game mode loaded successfully from the archive; the default-launch smoke ran for over five minutes without a fatal or asset-loading error. Cold-start PSO hitches and an audio-buffer underrun were observed; warm-run performance was not certified.

Final portable delta: `CampusCenter_R25_Combined_Delta_R02.zip`, SHA-256 `ef9d025d645474a29d26f48ecc0032f83ea05bb051581d66195c3c1f8241b7b2`. 39 new assets plus one NEW R25 map, count2,231. It supersedes the R24/R01 handoff. Frozen R21/R22/R24 and R01 ZIP are unchanged. R25 has explicit NoCollision trophy profiles; original cases retain BlockAll.

The approved case footprints are unchanged to1.4e-12cm, unit scale retained. Both five-meter case-front walks pass northbound and southbound before/after. Original14 paired doorway/fitness tests retain two existing failures and no new regressions. All seven B05 bench donors remain preserved in native geometry; four replacement equipment meshes bind approved native materials after save/reload and use conventional rendering after Nanite artifact isolation. No project/renderer/global OS settings changes.

R25 differs from rendered R24 only in two invisible trophy collision profiles. Final screen and clearance captures are R25. Actual preview gallery: `native-preview/review-r25.html`. Package/cook/smoke evidence: `build-status-r25.json`. Private Library identities: `library-receipts-r25.json`.

Vive R04 has no R22 inset actor: create exactly one plane on verified reception TV65 using the create-if-missing manifest. Preserve TV frame/wall and cafeTV43. R25/R02 is clear for read-only consumer preflight; headset/cooked Vive validation is downstream work. Source and prior releases were not written. The only out-of-workspace build write was Unreal's reversible staging cache, approved by automatic review. No publishing.
''')
