from pathlib import Path
import json,hashlib,shutil,zipfile
R=Path(__file__).parent/'combined_r01';C=Path(__file__).parent/'slideshow_r01/unreal_project/Content';P=R/'integration_payload_r25_r02';P.mkdir(exist_ok=True);old=json.loads((R/'integration_payload_final/portable-implementation-manifest.json').read_text());records=[]
for row in old['files']:
 if row['path'].endswith('.umap'):continue
 src=C/row['path'].removeprefix('Content/');assert hashlib.sha256(src.read_bytes()).hexdigest()==row['sha256'];dest=P/row['path'];dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(src,dest);records.append(row)
maprel='Campus/Maps/CampusCenter_FA26_Desktop_R25_CombinedReview.umap';src=C/maprel;b=src.read_bytes();assert not any(s.encode() in b or s.encode('utf-16le') in b for s in ['mikef','C:/Users','C:\\Users']);dest=P/'Content'/maprel;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(src,dest);records.append({'path':'Content/'+maprel,'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)})
proof=json.loads((R/'r25-final-native-preservation.json').read_text());assert proof['final_actor_count']==2231;new=proof['new_trophies'];assert len(new)==2 and all(v['collision_profile']=='NoCollision' and 'NO_COLLISION: 0' in v['collision_enabled'] for v in new.values())
hall=json.loads((R/'r25-case-hall-walking/validation.json').read_text());assert not hall.get('error') and hall['regressions']==[] and all(t['reached'] for m in hall['maps'].values() for t in m['tests']);hall['method']='Two paired five-meter athletics case-front walks, northbound and southbound; actual baseline Character Movement and capsule; final R25 map.';(P/'case-hall-walking-validation.json').write_text(json.dumps(hall,indent=2))
old.update({'target_map':'/Game/Campus/Maps/CampusCenter_FA26_Desktop_R25_CombinedReview','actor_count':2231,'files':records,'revision':'R25/R02 supersedes R24/R01 contract inconsistencies; R24 map and R01 ZIP remain frozen','trophy_collision':'Explicit NoCollision profile and disabled collision, independently saved/reopened; original cases BlockAll','Vive_integration':'Vive R04 lacks the R22 inset actor. Create exactly one inset plane on verified reception TV65 using reception_bsod_create_if_missing spec; do not alter TV frame/wall or cafeTV43. Apply four equipment mesh references and approved native overrides, two trophy actors and two in-place case rotations. Keep approved footprints, renderer, pawn and doors. Do not overwrite an existing Vive map.','status':'Cook R25 passed, native profile/count checks passed, two case-front walks pass both directions before/after; desktop staging separately in progress'})
screen=next(v['after'] for k,v in proof['changed_original_actors'].items() if k=='StaticMeshActor_2059');old['reception_bsod_create_if_missing']={'label':screen['label'],'class':'/Script/Engine.StaticMeshActor','verified_reception_TV65_actor':'StaticMeshActor_1591','mesh':screen['mesh'],'location_cm':screen['location'],'rotation_pitch_roll_yaw':screen['rotation'],'scale':screen['scale'],'materials':screen['materials'],'collision_profile':screen['collision_profile'],'collision_enabled':screen['collision_enabled'],'cast_shadow':screen['cast_shadow'],'do_not_modify':'Reception TV65 cube/frame/wall and cafe portrait TV43'}
(P/'portable-implementation-manifest.json').write_text(json.dumps(old,indent=2))
m=json.loads((R/'final-combined-implementation-manifest.json').read_text());m.update({'map':old['target_map'],'map_sha256':records[-1]['sha256'],'actor_count':2231,'schema':'CampusCenter.combined-review.v3','cooking':'R25 incremental cook exit 0, zero errors; unchanged C++/assets, new map recooked','verification':'Explicit trophy NoCollision profiles saved/reopened; count2231; prior protected-geometry/walking evidence remains valid; R25 case-front walks pass in both directions.'});placement=json.loads((R/'trophies/placement-manifest.json').read_text());placement['map']=old['target_map'];m['trophy_integration']=placement;(P/'final-combined-implementation-manifest.json').write_text(json.dumps(m,indent=2));(P/'placement-manifest.json').write_text(json.dumps(placement,indent=2))
for src,name in [(R/'r25-final-native-preservation.json','final-native-preservation.json'),(R/'r25-trophy-collision-proof.json','trophy-collision-proof.json'),(R/'trophies/approved-footprint-preservation.json','approved-footprint-preservation.json'),(R/'native-material-binding-repair.json','native-material-binding-repair.json'),(R/'native-bench-preservation.json','native-bench-preservation.json'),(R/'final-walking/validation.json','walking-validation.json'),(R/'portable-dependency-closure.json','portable-dependency-closure.json'),(R/'trophies/case-orientation-fix.json','case-orientation-fix.json'),(R/'trophies/native-assets.json','native-assets.json')]:shutil.copy2(src,P/name)
(P/'README.md').write_text('CampusCenter R25 Combined Review, portable delta R02. Supersedes R24/R01. 39 unchanged new asset packages plus one NEW R25 map. Saved/reopened count2231. Two trophy actors use explicit NoCollision profile; case enclosure BlockAll. Case footprints preserved within1.4e-12cm. Two5m case-front walks pass both directions. Four equipment native material references verified after reload; seven corrected bench donors preserved. For Vive R04 create one reception TV65 BSOD inset from the manifest; no R22 screen is assumed. Frozen R21/R22/R24 and R01 ZIP untouched. No renderer/project/OS changes or publishing. Actual approved visual previews are in the sibling native-preview folder; R25 differs visually from R24 in no way (two collision profiles only). Desktop package status tracked separately.')
z=R/'CampusCenter_R25_Combined_Delta_R02.zip';assert not z.exists()
with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as out:
 for q in sorted(P.rglob('*')):
  if q.is_file():out.write(q,q.relative_to(P).as_posix())
identity={'archive':z.name,'sha256':hashlib.sha256(z.read_bytes()).hexdigest(),'bytes':z.stat().st_size,'map':old['target_map'],'map_sha256':records[-1]['sha256'],'actor_count':2231,'new_assets':39,'new_map':1,'trophy_saved_profiles':'NoCollision','case_footprints_preserved':True,'case_hall_before_after_pass':[True,True],'R01_sha256_still':hashlib.sha256((R/'CampusCenter_R24_Combined_Delta_R01.zip').read_bytes()).hexdigest(),'consumer_status':'CLEAR FOR READ-ONLY VIVE PREFLIGHT; no competing heavy cook; desktop staging/smoke remains separate'};assert identity['R01_sha256_still']=='37f95bd6b341a733d0d8472bc0e0f8d9a264267d62e451116ee34117f3c87cc8';(R/'shared-consumer-handoff-r25-r02-identity.json').write_text(json.dumps(identity,indent=2));print(json.dumps(identity))
