# Invoked inside equipment integration after ROOT/OUT/A/L/E/AT are initialized.
M=unreal.MaterialEditingLibrary;NSBSOD='/Game/Campus/ReceptionBSODR01'
world=unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world();unreal.SystemLibrary.execute_console_command(world,'Interchange.FeatureFlags.Import.PNG 0')
task=unreal.AssetImportTask();task.filename=str(OUT/'bsod_source/ReceptionTV65_BSOD_R01.png');task.destination_path=NSBSOD;task.automated=True;task.save=True;task.factory=unreal.TextureFactory();task.replace_existing=True;AT.import_asset_tasks([task])
tex=unreal.load_asset(task.imported_object_paths[0]);tex.get_editor_property('asset_import_data').scripted_add_filename('',0,'Fictional comic BSOD; source in bsod_source');tex.set_editor_property('compression_settings',unreal.TextureCompressionSettings.TC_EDITOR_ICON);tex.set_editor_property('mip_gen_settings',unreal.TextureMipGenSettings.TMGS_NO_MIPMAPS);E.save_loaded_asset(tex)
mat=AT.create_asset('M_ReceptionBSOD',NSBSOD,unreal.Material,unreal.MaterialFactoryNew());assert mat;mat.set_editor_property('shading_model',unreal.MaterialShadingModel.MSM_UNLIT);mat.set_editor_property('two_sided',True)
sample=M.create_material_expression(mat,unreal.MaterialExpressionTextureSampleParameter2D);sample.set_editor_property('texture',tex);sample.set_editor_property('parameter_name','ScreenTexture')
uv=M.create_material_expression(mat,unreal.MaterialExpressionTextureCoordinate);custom=M.create_material_expression(mat,unreal.MaterialExpressionCustom);custom.set_editor_property('output_type',unreal.CustomMaterialOutputType.CMOT_FLOAT2);ci=unreal.CustomInput();ci.set_editor_property('input_name','UV');custom.set_editor_property('inputs',[ci]);custom.set_editor_property('code','return float2(UV.x,1.0-UV.y);');M.connect_material_expressions(uv,'',custom,'UV');M.connect_material_expressions(custom,'',sample,'UVs')
mul=M.create_material_expression(mat,unreal.MaterialExpressionMultiply);brightness=M.create_material_expression(mat,unreal.MaterialExpressionScalarParameter);brightness.set_editor_property('parameter_name','Brightness');brightness.set_editor_property('default_value',0.8);M.connect_material_expressions(sample,'RGB',mul,'A');M.connect_material_expressions(brightness,'',mul,'B')
eye=M.create_material_expression(mat,unreal.MaterialExpressionEyeAdaptationInverse);alpha=M.create_material_expression(mat,unreal.MaterialExpressionConstant);alpha.set_editor_property('r',1.0);names=M.get_material_expression_input_names(eye);M.connect_material_expressions(mul,'',eye,str(names[0]));M.connect_material_expressions(alpha,'',eye,str(names[1]));M.connect_material_property(eye,'',unreal.MaterialProperty.MP_EMISSIVE_COLOR);M.recompile_material(mat);E.save_loaded_asset(mat)
screen=next(a for a in A.get_all_level_actors() if a.get_actor_label()=='ReceptionTV65_Slideshow_R01_TEMP');screen_name=screen.get_name();screen.static_mesh_component.set_material(0,mat);screen.set_actor_label('ReceptionTV65_BSOD_R01');screen.tags=['ReceptionTV65BSODR01','FictionalComicDisplay']
bsod_manifest={'actor_name':screen_name,'actor_label':'ReceptionTV65_BSOD_R01','texture':tex.get_path_name(),'material':mat.get_path_name(),'brightness':0.8,'display':'Static fictional Windows-style blue error screen; user approved replacement content','cycling':False,'audio':False,'qr_or_external_destination':False,'os_effects':False,'prior_R22_screen_unchanged':True}
