import unreal,pathlib,json,math
R=pathlib.Path(__file__).parent/'combined_r01/trophies';E=unreal.EditorAssetLibrary;L=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem);A=unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
base='/Game/Campus/Maps/CampusCenter_FA26_Desktop_R23_EquipmentBSOD';target='/Game/Campus/Maps/CampusCenter_FA26_Desktop_R24_CombinedReview';assert L.load_level(base);assert not E.does_asset_exist(target);assert E.duplicate_asset(base,target);assert L.load_level(target);before={a.get_name():(a.get_actor_location().to_tuple(),a.get_actor_rotation().to_tuple(),a.get_actor_scale3d().to_tuple()) for a in A.get_all_level_actors()};rows=[]
assets=json.loads((R/'native-assets.json').read_text())
for name,y,z,case in [('SilverCup',-2355,109.0999984741211,0),('RegionalPlaque',-2120,65.10000610351562,1)]:
 row=next(r for r in assets if r['name']==name);n=unreal.load_asset(row['asset']);a=A.spawn_actor_from_class(unreal.StaticMeshActor,unreal.Vector(-2612.5,y,z-row['bounds_cm'][0][2]));a.set_actor_label(name+'_AthleticsCase_TR27R01');a.set_actor_rotation(unreal.Rotator(yaw=-90),False);c=a.static_mesh_component;c.set_static_mesh(n);c.set_collision_enabled(unreal.CollisionEnabled.NO_COLLISION);a.tags=['TrophyTR27R01','BlankGenericDisplay'];o,e=a.get_actor_bounds(False);lo=(o-e).to_tuple();hi=(o+e).to_tuple();assert abs(lo[2]-z)<.01;assert lo[0]>-2640 and hi[0]<-2585;assert hi[2]<([146.9,106.9][case]);rows.append({'actor':a.get_name(),'label':a.get_actor_label(),'asset':n.get_path_name(),'case':case,'shelf_top_cm':z,'bounds_cm':[lo,hi],'shelf_contact_error_cm':abs(lo[2]-z),'collision':'NoCollision; original case retained'})
assert L.save_current_level();assert L.load_level(target);assert all((a.get_actor_location().to_tuple(),a.get_actor_rotation().to_tuple(),a.get_actor_scale3d().to_tuple())==before[a.get_name()] for a in A.get_all_level_actors() if a.get_name() in before);assert len(A.get_all_level_actors())==len(before)+2
(R/'placement-manifest.json').write_text(json.dumps({'map':target,'placements':rows,'existing_actor_transforms_preserved':True},indent=2));unreal.SystemLibrary.quit_editor()

