import unreal,pathlib,json
R=pathlib.Path(__file__).parent/'combined_r01';L=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem);A=unreal.get_editor_subsystem(unreal.EditorActorSubsystem);assert L.load_level('/Game/Campus/Maps/CampusCenter_FA26_Desktop_R25_CombinedReview');before=json.loads((R/'baseline-actors-r22.json').read_text());after={}
for a in A.get_all_level_actors():
 c=getattr(a,'static_mesh_component',None);after[a.get_name()]={'label':a.get_actor_label(),'location':a.get_actor_location().to_tuple(),'rotation':a.get_actor_rotation().to_tuple(),'scale':a.get_actor_scale3d().to_tuple(),'hidden':bool(a.get_editor_property('hidden')),'tags':[str(t) for t in a.tags],'mesh':c.static_mesh.get_path_name() if c and c.static_mesh else None,'materials':[c.get_material(i).get_path_name() if c.get_material(i) else None for i in range(c.get_num_materials())] if c else [],'collision_enabled':str(c.get_collision_enabled()) if c else None,'collision_profile':str(c.get_collision_profile_name()) if c else None,'cast_shadow':bool(c.get_editor_property('cast_shadow')) if c else None}
# JSON round-trip normalizes vectors/tuples.
after=json.loads(json.dumps(after));changes={k:{'before':v,'after':after.get(k)} for k,v in before.items() if after.get(k)!=v};expected=set(json.loads((R/'allowed-actor-differences.json').read_text())['allowed_actor_names']) if False else {'StaticMeshActor_1510','StaticMeshActor_2035','StaticMeshActor_2036','StaticMeshActor_2037','StaticMeshActor_1813','StaticMeshActor_1814',next(k for k,v in before.items() if v['label']=='ReceptionTV65_Slideshow_R01_TEMP')};assert set(changes)==expected,(set(changes),expected);added={k:v for k,v in after.items() if k not in before};assert len(added)==2;checks=[]
for a in A.get_all_level_actors():
 if a.get_name() not in expected or a.get_name() not in ['StaticMeshActor_1510','StaticMeshActor_2035','StaticMeshActor_2036','StaticMeshActor_2037']:continue
 c=a.static_mesh_component;n=c.static_mesh;b=n.get_editor_property('body_setup');assert not n.get_editor_property('nanite_settings').enabled;assert c.get_collision_enabled()==unreal.CollisionEnabled.QUERY_AND_PHYSICS;assert b.get_editor_property('collision_trace_flag')==unreal.CollisionTraceFlag.CTF_USE_COMPLEX_AS_SIMPLE;assert c.get_collision_profile_name()=='BlockAll';checks.append(a.get_name())
(R/'r25-final-native-preservation.json').write_text(json.dumps({'map':'CampusCenter_FA26_Desktop_R25_CombinedReview','baseline_actor_count':len(before),'final_actor_count':len(after),'changed_original_actors':changes,'new_trophies':added,'equipment_collision_contract_pass':checks,'renderer_choice':'Nanite disabled only on four replacement meshes after actual viewport artifact isolation'},indent=2));unreal.SystemLibrary.quit_editor()


