from pathlib import Path
import json,html,base64,io,hashlib,zipfile,sys
from PIL import Image
R=Path(__file__).parent;B=R.parent/'CampusCenter-print-r25-r01';source=json.loads((R/'furniture_source.json').read_text());change=json.loads((R/'changed_piece_manifest.json').read_text());qc=json.loads((R/'digital_validation.json').read_text());families=change['families']
captions={'ground_furniture_overview':'1:87.5 furnished ground display with simplified seating, benches, trainer fixtures and bleacher banks. Actual fused print geometry.','ground_furniture_top':'Ground top view. Room shell and floor footprint retained; added furniture is filled vertically to supporting floors.','upper_furniture_overview':'R02 upper enclosed furnished variant with corrected B05 Fitness envelopes and useful additional fitness machines.','upper_furniture_top':'Upper top view retains gym/gallery/Commons voids.','bleachers':'Reused bleacher bank becomes a supported stepped silhouette. Fine rails and open under-seat spaces are merged for print.','locker_benches':'Locker bench additions become supported solid masses. The actual source placement governs; no product dimension claim.','trainer':'Trainer fixtures represented by strengthened, floor-filled silhouettes, with tiny rods/handles merged.','fitness_connected_overview':'Corrected existing Fitness donor group plus 20 additional Fitness placement groups. Source shafts, racks and legs become vertically filled, broadened masses attached to the floor; thin wall racks omitted.','supported_rack_detail':'Actual corrected supported-rack print envelope. B05 source proof records shaft overlap with both uprights for five assemblies. Printed form is a schematic connected support envelope, not manufacturer rack hardware.','standalone_bench_detail':'Actual standalone-bench print envelope. Loaded bars were removed in B05 from both standalone benches before this print reconstruction. Old Fitness donor envelopes were replaced, not retained beneath a union.','miniature_assembled':'Separate 1:350 ground/upper/roof display with supported Fitness masses. Existing installation levels and removable interfaces retained; roof grid unchanged.','miniature_separated':'Actual miniature geometry separated for presentation only: upper +35 mm and roof +70 mm, restored in the saved editable source.'}
intro=f'''<h1>CampusCenter furniture print variant R02</h1><p>Separate derivative of the validated v25 print package and preserved furniture R01. <b>63 enhancement placement groups carried</b> from pinned B05: 23 geometry reuses and 40 generic estimated representations. In addition, 37 existing Fitness source meshes are replaced from the corrected complete donor group. Source dimensions and styles remain estimates where labeled as such. Eleven photo presentations, two trophy cases and three thin wall racks are omitted.</p><p>B05 is the donor explicitly named by fitness_support_v26_r02. Its read-only proof records five shafts intersecting both supporting uprights, loaded bars removed from two standalone benches, and 6,589 other meshes unchanged. The upper furniture field is reconstructed without the old Fitness donor group before B05 is added. Support hardware/product safety is not certified.</p><p>Four large variants retain 1:87.5, 4.8 mm floors, overall dimensions within 0.003 mm and exact v25 split coordinates. Supported maximum-surface envelopes use 0.5 mm sampling plus one-cell broadening per side. The separate 1:350 assembly retains 0 / 12.192 / 23.077714 mm installation levels and the original roof grid. No intentional room-envelope edits.</p><p>The acrylic family trims added furniture within existing pane/channel insertion envelopes; original frames/panes are untouched. Nominal 1.85 mm slots, 1.5875 mm acrylic and 0.2625 mm total thickness clearance remain. Optional partitions, cut sheets and coupons retain original v25 conventions.</p>'''
parts=['<!doctype html><html><meta charset="utf-8"><title>CampusCenter furniture print variant</title><style>body{font:17px system-ui;color:#183045;background:#edf2f5;max-width:1100px;margin:auto;padding:30px}figure{background:white;padding:18px;margin:25px 0;border-radius:12px}img{width:100%}figcaption{line-height:1.5}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:8px;border:1px solid #becbd5;text-align:left;overflow-wrap:anywhere}code{overflow-wrap:anywhere}</style><body>',intro]
for name,caption in captions.items():
 im=Image.open(R/'review'/(name+'.png')).convert('RGB');out=io.BytesIO();im.save(out,format='JPEG',quality=88,optimize=True);parts.append('<figure><img alt="'+name+'" src="data:image/jpeg;base64,'+base64.b64encode(out.getvalue()).decode()+'"><figcaption>'+html.escape(caption)+'</figcaption></figure>')
parts.append(f'<h2>Digital evidence and limits</h2><p>{len(qc["stl_files"])} STLs and {len(qc["three_mf_files"])} 3MFs reopened: watertight, consistent winding, no zero-area faces, explicit connected physical pieces, Z=0 and bed fit where applicable. Added acrylic insertion collisions: zero. Individual pieces fit the established 290 × 300 × 315 mm envelope; full assembly files are references, not single-bed jobs. STEP receipts report reopened B-representation bounds and volume. The saved editable file is Blender 5.0 format and must be opened in Blender 5.0 or a compatible newer version.</p><p><b>Untested:</b> slicing, toolpaths, physical printer/material response, coupon/acrylic fit and assembly acceptance. There is no exhaustive medial-axis feature-thickness certification. Broadening is constructive reinforcement; floor/cut clipping can leave smaller tips, and tall/narrow masses need slicer review. No supported installed print slicer was found; no installation or printer operation occurred.</p>')
for family in families:
 d=json.loads((R/family['family']/'validation.json').read_text());parts.append('<h2>'+family['family']+'</h2><p>'+str(len(d['tiles']))+' actual printed parts in six bed regions. Suffixes identify disconnected pieces; variant suffix assignment is ordered by component volume. Use these variant offsets, not baseline suffix assumptions. STL and 3MF share the exact stem.</p><table><tr><th>Exact piece ID</th><th>X × Y × Z mm</th><th>Assembly offset mm</th></tr>')
 for t in d['tiles']:parts.append('<tr><td>'+t['name']+'</td><td>'+' × '.join(f'{x:.3f}' for x in t['dimensions_mm'])+'</td><td>'+' / '.join(f'{x:.3f}' for x in t['assembly_offset_mm'])+'</td></tr>')
 parts.append('</table><p>Changed regions: '+', '.join(x['region'] for x in family['regions'] if x['changed_geometry'])+'. Exact source/variant filenames and volume changes are in changed_piece_manifest.json.</p>')
parts.append('<h2>Source and preservation</h2><p>B05 SHA-256: <code>'+source['sha256']+'</code>. Accepted v25 and both previous print packages were only read. Desktop/Vive and frozen enhancement release files were not modified. This variant does not incorporate Unreal-only photo/art assets.</p></body></html>')
review=R/'CampusCenter_Furniture_Print_Review_R02.html';review.write_text(''.join(parts),encoding='utf-8');assert review.stat().st_size<20_000_000
notes='CampusCenter furniture print variant\n\n'+intro.replace('<p>','\n\n').replace('</p>','').replace('<b>','').replace('</b>','').replace('<h1>','').replace('</h1>','')+'\n\nSee the compact review, changed_piece_manifest.json, digital_validation.json and each family validation/STEP receipt. Print each separate print_tiles file at millimetre scale with no fit-to-bed scaling. Butt join on a supporting board; no new pins/sockets. Existing acrylic cut sheets/coupon and optional partition files are copied unchanged under original_accessories. Physical/slicer acceptance remains untested. Original v25 assembly notes govern retained interfaces.\n'
(R/'ASSEMBLY_AND_LIMITS.txt').write_text(notes,encoding='utf-8')
if '--review-only' in sys.argv:
 print('REVIEW_READY',review.stat().st_size);sys.exit(0)
manifest=[]
for p in R.rglob('*'):
 if not p.is_file() or p.suffix in ['.log','.zip'] or '_raw.stl' in p.name or p.name.endswith('_addition_raw.stl') or p.name=='delivery_manifest.json':continue
 manifest.append({'file':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(R/'delivery_manifest.json').write_text(json.dumps(manifest,indent=2));archive=R/'CampusCenter_Furniture_Print_V26_R02.zip'
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for x in manifest:z.write(R/x['file'],x['file'])
 z.write(R/'delivery_manifest.json','delivery_manifest.json')
with zipfile.ZipFile(archive) as z:assert z.testzip() is None
print('PACKAGED',review.stat().st_size,archive.stat().st_size,len(manifest),flush=True)
