import pathlib,json,hashlib,zipfile,html
O=pathlib.Path(__file__).parent;m=json.loads((O/'replacement_manifest.json').read_text());checks=json.loads((O/'DELIVERY_CHECKS.json').read_text())
captions=[('baseline_representatives.png','B05 schematic donors','Solid rack side panels, minimal treadmill and generic pulldown shape.'),('improved_representatives.png','EQ27 assemblies','Open supported rack, complete treadmill frame and cable/weight-stack pulldown.'),('rack_detail.png','Rack and retained bench','Five stations use unchanged corrected B05 benches and loaded shafts with two supporting ledges.'),('treadmill_detail.png','Treadmill','Belt, deck crossmembers, rollers, leveling supports, handrails and blank console.'),('pulldown_detail.png','Pulldown','Guided individual weight plates, overhead pulleys and continuous cable route; supported seat and thigh pads.'),('press_core_detail.png','Core and shoulder press','Distinct chest pad/pivot and press arm assemblies; supported bases and seats.')]
cards=''.join(f'<figure><a href="previews/{n}"><img src="previews/{n}" alt="{html.escape(t)}"></a><figcaption><strong>{html.escape(t)}</strong><p>{html.escape(d)}</p></figcaption></figure>' for n,t,d in captions)
rows=''.join(f'<tr><td>{r["source_marker"]}</td><td>{html.escape(r["label"])}</td><td>{r["id"]}</td><td>{r["parts_count"]}</td></tr>' for r in m['replacements'])
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CampusCenter EQ27 Equipment Review</title><style>body{{margin:0;background:#eef1f2;color:#17242c;font:16px/1.5 system-ui}}main{{max-width:1240px;margin:auto;padding:36px}}h1{{font-size:36px;margin:0}}.grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}}figure{{margin:0;background:white;border-radius:14px;overflow:hidden}}img{{width:100%;display:block}}figcaption{{padding:20px}}p{{margin:8px 0 18px}}a{{color:#176567}}table{{border-collapse:collapse;width:100%;background:white}}td,th{{padding:10px;text-align:left;border-bottom:1px solid #ddd}}code{{font-size:13px}}@media(max-width:750px){{.grid{{grid-template-columns:1fr}}main{{padding:18px}}table{{font-size:12px}}}}</style><main><h1>CampusCenter equipment · EQ27 R01</h1><p>14 editable assemblies: six treadmills, five rack stations, core, pulldown and shoulder press. Approved world positions and traced footprints retained. All unspecified dimensions and mechanics are estimates.</p><p><a href="CampusCenter_Equipment_Editable_EQ27_R01.blend">Editable Blender source</a> · <a href="exports/Equipment_EQ27_R01_World.glb">All replacement assemblies</a> · <a href="exports/R25_U218_Furniture_EQ27_R01_Complete.glb">Complete legacy fitness actor replacement</a> · <a href="AUDIT_AND_INTEGRATION.txt">Audit and integration instructions</a></p><div class="grid">{cards}</div><h2>Exact replacement IDs</h2><table><thead><tr><th>Plan marker</th><th>Equipment</th><th>New assembly</th><th>Parts</th></tr></thead><tbody>{rows}</tbody></table><h2>Compatibility and preservation</h2><p>16 exports reopened successfully; source and imported world bounds match within 0.001 mm. Seven bench donors match B05 geometry exactly. Two standalone benches have no loaded bars; all five rack shafts have two supporting ledges. Source mesh components are closed. Exports have no external texture dependencies.</p><p>B05 and Desktop R21 Support hashes remain unchanged. Native collision/traversal checks are pending isolated Unreal integration. Preserve complex-as-simple collision and Query and Physics; bind materials by name using <a href="material_compatibility.json">the exact compatibility mapping</a>.</p><p><a href="replacement_manifest.json">Replacement manifest</a> · <a href="validation.json">Export and support checks</a> · <a href="source_integrity_after.json">Frozen source integrity</a> · <a href="equipment_inventory.csv">Equipment inventory</a></p></main></html>'''
(O/'Equipment_Review.html').write_text(page,encoding='utf-8')
page=page.replace('16 exports reopened',str(checks['export_files'])+' exports reopened')
page=page.replace('0.001 mm','0.01 mm')
(O/'Equipment_Review.html').write_text(page,encoding='utf-8')
names=['CampusCenter_Equipment_Editable_EQ27_R01.blend','AUDIT_AND_INTEGRATION.txt','Equipment_Review.html','equipment_inventory.csv','b05_inventory.json','replacement_manifest.json','validation.json','DELIVERY_CHECKS.json','material_compatibility.json','native_integration_evidence.json','source_integrity_before.json','source_integrity_after.json','preview_contract.json','preview_validation.json','audit.py','build_equipment.py','finalize_staging.py','clean_staging.py','render_previews.py','validate_exports.py','export_runtime_joined.py','native_contract.py','package_evidence.py','make_handoff.py']
paths=[O/n for n in names]+sorted((O/'exports').glob('*.glb'))+sorted((O/'previews').glob('*.png'))+[O/'previews/render_results.json']
paths += [O/'source_dependency_check.json',O/'check_source_dependencies.py']
sums=[{'file':str(p.relative_to(O)).replace('\\','/'),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in paths];(O/'SHA256SUMS.json').write_text(json.dumps(sums,indent=2));paths.append(O/'SHA256SUMS.json')
bundle=O.parent/'CampusCenter_Equipment_EQ27_R01.zip'
with zipfile.ZipFile(bundle,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for p in paths:z.write(p,str(p.relative_to(O)))
with zipfile.ZipFile(bundle) as z:assert z.testzip() is None
print('BUNDLE',str(bundle),'bytes',bundle.stat().st_size,'sha256',hashlib.sha256(bundle.read_bytes()).hexdigest(),'files',len(paths))
